name: Run Unit Test and Upload Coverage Report

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Install ROS2 Humble
        run: |
          sudo apt update
          sudo apt install -y curl gnupg2 lsb-release
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo sh -c 'echo "deb http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list'
          sudo apt update
          sudo apt install -y ros-humble-desktop

      - name: Install Gazebo
        run: |
          sudo apt update
          sudo apt install -y gazebo libgazebo-dev

      - name: Install build packages
        run: |
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake make
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Configure CMake flags and build executables
        run: |
          source /opt/ros/humble/setup.bash
          source /usr/share/gazebo/setup.sh
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/ --target random_test --clean-first

      - name: List build directory
        run: ls -R build

      - name: Run Random Test
        run: ./build/test/random_test

      - name: Generate Coverage Report
        run: |
          lcov --capture --directory build/ --output-file build/coverage.info
          lcov --remove build/coverage.info '/usr/*' '*/_deps/*' --output-file build/coverage_filtered.info
          mv build/coverage_filtered.info build/coverage.info

      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.info
          fail_ci_if_error: true
          verbose: true
