name: Run Unit Test and Upload Coverage Report

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  build-run-upload:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v3

      - name: Install build packages
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo apt install -y doxygen lcov gcovr
          sudo apt-get install -y libopencv-dev
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake make
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib


      - name: Configure CMake flags and build executables
        run: |
          cmake -D WANT_COVERAGE=ON -D CMAKE_BUILD_TYPE=Debug -S ./ -B build/
          cmake --build build/ --target random_test --clean-first

      - name: List build directory
        run: ls -R build

      - name: Run Random Test
        run: ./build/test/random_test

      - name: Generate Coverage Report
        run: |
          lcov --capture --directory build/ --output-file build/coverage.info
          lcov --remove build/coverage.info '/usr/*' '*/_deps/*' --output-file build/coverage_filtered.info
          mv build/coverage_filtered.info build/coverage.info

      - name: Upload coverage result to CodeCov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage.info
          fail_ci_if_error: true
          verbose: true
